version: '3'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "8194:1194/tcp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    environment:
      - EASYRSA_BATCH=1
      - EASYRSA_REQ_CN=sdgoo
      - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      vpn_net:
        ipv4_address: 172.18.0.2
    command: ["ovpn_run"]

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
