version: '3'
services:
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "8194:1194/udp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    environment:
      - EASYRSA_BATCH=1
      - EASYRSA_REQ_CN=changeme
      - TZ=Asia/Shanghai
    dns:
      - 8.8.8.8
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - vpn_net
    command: ["ovpn_run"]

networks:
  vpn_net:
    driver: bridge
